### ISSUE TITLE
Blender 3.x crashes when using meshstats ....

### ISSUE THREAD

**Issue by nurb2kea** [muhuk/meshstats#1]
Hi,

just noticed that the 3D-Print Toolbox Addon crashes in blender 3.x
(https://developer.blender.org/T89311)

Same with meshstats, and I'm pretty sure the problem is the same, as both addons do basically the same, one can select the found odd mesh parts, but!

Since both addons are useful, I wanna let you know my screenings.

I'm using latest Mac build blender-3.0.0-alpha+cycles-x.e3ca9ccc98af-darwin.x86_64-release.
But other OS's have the same problem.

Hope that helps

Thanks in advance

**Comment by muhuk** [comment]
Hi @nurb2kea,
Thanks for the report. I haven't done anything for 3.x support so this is not a big surprise. I'll see the API changes for 3.x when it turns beta.

**Comment by muhuk** [comment]
I just checked with `blender-3.0.0-beta+v30.348d7c35a9f9-linux.x86_64-release` and it seems like this issue went away. Thanks for reporting anyway. Closing this.
